import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RobloxFile } from 'rbxm-parser';
const app=express(),PORT=process.env.PORT||3000,__dirname=path.dirname(fileURLToPath(import.meta.url));app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
async function json(url,o={}){const r=await fetch(url,o),t=await r.text();let d;try{d=JSON.parse(t)}catch{}if(!r.ok)throw Object.assign(new Error(`Roblox ${r.status}`),{status:r.status});return d}
async function user(name){const d=await json('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({usernames:[name],excludeBannedUsers:false})});if(!d?.data?.[0])throw Object.assign(new Error('Usuário não encontrado'),{status:404});return d.data[0]}
async function avatar(id){try{return await json(`https://avatar.roblox.com/v4/avatar/users/${id}`)}catch{return json(`https://avatar.roblox.com/v1/users/${id}/avatar`)}}
async function wearing(id){try{return (await json(`https://avatar.roblox.com/v1/users/${id}/currently-wearing`))?.assetIds||[]}catch{return[]}}
async function preview(id){try{return (await json(`https://thumbnails.roblox.com/v1/users/avatar?userIds=${id}&size=420x420&format=Png&isCircular=false`))?.data?.[0]?.imageUrl||null}catch{return null}}
function ids(a,w){const s=new Set((w||[]).map(Number));for(const x of a?.assets||[])s.add(Number(x.id));return [...s].filter(Number.isSafeInteger)}
function urls(v,out=[]){if(typeof v==='string'&&v.startsWith('https://'))out.push(v);else if(Array.isArray(v))v.forEach(x=>urls(x,out));else if(v&&typeof v==='object')Object.values(v).forEach(x=>urls(x,out));return [...new Set(out)]}
async function assetBytes(id){const d=await json(`https://assetdelivery.roblox.com/v2/assetId/${id}`,{headers:{accept:'application/json'}}),url=urls(d)[0];if(!url)return null;const r=await fetch(url,{redirect:'follow'});if(!r.ok)return null;return Buffer.from(await r.arrayBuffer())}
function simple(v){if(v==null||['string','number','boolean'].includes(typeof v))return v;if(Array.isArray(v))return v.map(simple);if(typeof v==='object'){const o={};for(const k of ['X','Y','Z','R','G','B','Name','Value','AssetId','MeshId','TextureID','TextureId','MeshType','Scale','Offset','Position','CFrame','Size','Color','Transparency'])if(k in v)o[k]=simple(v[k]);return Object.keys(o).length?o:String(v)}return String(v)}
function flatten(inst,out=[]){if(!inst)return out;const cls=inst.ClassName||inst.className||inst.constructor?.name||'Instance',props={};for(const k of ['Name','MeshId','TextureID','TextureId','MeshType','Scale','Offset','Position','CFrame','Size','Color','Transparency','AttachmentPoint']){try{const v=inst[k];if(v!==undefined)props[k]=simple(v)}catch{}}out.push({className:cls,properties:props});const ch=inst.Children||inst.children||[];for(const c of ch)flatten(c,out);return out}
async function parseAsset(id){try{const b=await assetBytes(id);if(!b)return {assetId:id,ok:false,error:'sem arquivo'};const f=RobloxFile.ReadFromBuffer(b);if(!f)return {assetId:id,ok:false,error:'RBXM inválido'};let roots=f.Instances||f.instances||f.Children||f.children||[];if(!Array.isArray(roots))roots=[];let list=[];for(const r of roots)flatten(r,list);if(!list.length&&typeof f.FindChildrenOfClass==='function'){for(const c of ['MeshPart','SpecialMesh','Accessory','Part','Shirt','Pants','Decal','Attachment']){try{for(const x of f.FindChildrenOfClass(c)||[])flatten(x,list)}catch{}}}return {assetId:id,ok:true,size:b.length,instances:list.slice(0,80)}}catch(e){return {assetId:id,ok:false,error:e.message}}
app.get('/api/avatar',async(req,res)=>{try{const name=String(req.query.username||'').trim(),u=await user(name),[a,w,p]=await Promise.all([avatar(u.id),wearing(u.id),preview(u.id)]);res.json({user:{id:u.id,name:u.name,displayName:u.displayName},previewUrl:p,avatar:a,wearing:w,assetIds:ids(a,w)})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.get('/api/avatar-model',async(req,res)=>{try{const name=String(req.query.username||'').trim(),u=await user(name),[a,w]=await Promise.all([avatar(u.id),wearing(u.id)]),all=ids(a,w),assets=[];for(let i=0;i<all.length;i+=4)assets.push(...await Promise.all(all.slice(i,i+4).map(parseAsset)));res.json({user:{id:u.id,name:u.name,displayName:u.displayName},avatar:a,assets})}catch(e){console.error(e);res.status(e.status||500).json({error:e.message})}});
app.get('/api/asset-file/:id',async(req,res)=>{const b=await assetBytes(Number(req.params.id));if(!b)return res.status(404).send('sem arquivo');res.type('application/octet-stream').send(b)});
app.get('/health',(_q,r)=>r.json({ok:true,mode:'rbxm-real-avatar-parser'}));app.listen(PORT,()=>console.log(`DES RBXM avatar parser :${PORT}`));