import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const app=express();const PORT=process.env.PORT||3000;const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
async function fetchJson(url,options={}){const r=await fetch(url,options),text=await r.text();let data;try{data=JSON.parse(text)}catch{data=null}if(!r.ok){const e=new Error(`Roblox request failed (${r.status})`);e.status=r.status;e.body=data??text;throw e}return data}
async function resolveUsername(username){const p=await fetchJson('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({usernames:[username],excludeBannedUsers:false})});const u=p?.data?.[0];if(!u){const e=new Error('Usuário Roblox não encontrado');e.status=404;throw e}return u}
async function fetchAvatarDefinition(id){try{return await fetchJson(`https://avatar.roblox.com/v4/avatar/users/${id}`)}catch{return fetchJson(`https://avatar.roblox.com/v1/users/${id}/avatar`)}}
async function fetchCurrentlyWearing(id){try{const d=await fetchJson(`https://avatar.roblox.com/v1/users/${id}/currently-wearing`);return Array.isArray(d?.assetIds)?d.assetIds:[]}catch{return[]}}
async function getFullBodyPreview(id){try{const d=await fetchJson(`https://thumbnails.roblox.com/v1/users/avatar?userIds=${id}&size=420x420&format=Png&isCircular=false`);return d?.data?.[0]?.imageUrl||null}catch{return null}}
function assetIdsFromAvatar(avatar,wearing){const ids=new Set((wearing||[]).map(Number).filter(Number.isSafeInteger));for(const a of avatar?.assets||[]){const id=Number(a?.id);if(Number.isSafeInteger(id))ids.add(id)}return [...ids]}
function deliveryLocations(data){const out=[];const walk=v=>{if(!v)return;if(typeof v==='string'&&/^https:\/\//i.test(v)){out.push(v);return}if(Array.isArray(v))return v.forEach(walk);if(typeof v==='object')for(const [k,x] of Object.entries(v)){if(/location|url/i.test(k))walk(x);else if(typeof x==='object')walk(x)}};walk(data);return [...new Set(out)]}
async function inspectDelivered(url){try{const r=await fetch(url,{redirect:'follow'}),bytes=Buffer.from(await r.arrayBuffer()),head=bytes.subarray(0,128).toString('utf8').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'');return {ok:r.ok,status:r.status,contentType:r.headers.get('content-type')||'',size:bytes.length,head}}catch(e){return {ok:false,error:e.message}}}
async function inspectAsset(assetId,deep=false){try{const r=await fetch(`https://assetdelivery.roblox.com/v2/assetId/${assetId}`,{headers:{accept:'application/json'}}),text=await r.text();let data=null;try{data=JSON.parse(text)}catch{}const locations=deliveryLocations(data),delivered=deep?await Promise.all(locations.slice(0,2).map(inspectDelivered)):[];return {assetId,status:r.status,ok:r.ok,contentType:r.headers.get('content-type'),data:data&&typeof data==='object'?data:null,locations,delivered}}catch(e){return {assetId,ok:false,error:e.message}}}
app.get('/api/avatar',async(req,res)=>{try{const username=String(req.query.username||'').trim();if(!/^[A-Za-z0-9_]{3,20}$/.test(username))return res.status(400).json({error:'Digite um username Roblox válido.'});const user=await resolveUsername(username);const [avatar,wearing,previewUrl]=await Promise.all([fetchAvatarDefinition(user.id),fetchCurrentlyWearing(user.id),getFullBodyPreview(user.id)]);res.json({user:{id:user.id,name:user.name,displayName:user.displayName},previewUrl,avatar,wearing,assetIds:assetIdsFromAvatar(avatar,wearing),mode:'asset-reconstruction'})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.get('/api/avatar-assets',async(req,res)=>{try{const username=String(req.query.username||'').trim(),user=await resolveUsername(username),[avatar,wearing]=await Promise.all([fetchAvatarDefinition(user.id),fetchCurrentlyWearing(user.id)]),ids=assetIdsFromAvatar(avatar,wearing),results=[];for(let i=0;i<ids.length;i+=4)results.push(...await Promise.all(ids.slice(i,i+4).map(id=>inspectAsset(id,true))));res.json({user:{id:user.id,name:user.name},count:ids.length,assets:results})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.get('/api/asset-file/:id',async(req,res)=>{try{const id=Number(req.params.id),info=await inspectAsset(id,false),url=info.locations?.[0];if(!url)return res.status(404).send('Asset sem arquivo entregue');const up=await fetch(url,{redirect:'follow'});if(!up.ok)return res.status(up.status).send('Arquivo indisponível');const type=up.headers.get('content-type');if(type)res.setHeader('content-type',type);res.send(Buffer.from(await up.arrayBuffer()))}catch(e){res.status(500).send('Falha')}});
app.get('/health',(_req,res)=>res.json({ok:true,mode:'real-avatar-delivered-files'}));
app.listen(PORT,()=>{console.log(`DES Roblox delivered asset inspector running on :${PORT}`);setTimeout(async()=>{try{const user=await resolveUsername('farm11za'),avatar=await fetchAvatarDefinition(user.id),wearing=await fetchCurrentlyWearing(user.id),ids=assetIdsFromAvatar(avatar,wearing);console.log('FARM_PROBE avatarAssets',JSON.stringify(avatar?.assets||[]));for(const id of ids){const x=await inspectAsset(id,true);console.log('FARM_PROBE',id,JSON.stringify(x.delivered))}}catch(e){console.error('FARM_PROBE_FAIL',e.message)}},1500)});